### ISSUE TITLE
v1 EOL? Migration Guide?

### ISSUE THREAD

**Issue by dylancaponi** [jwplayer/jwplatform-py#38]
How long will v1 continue being available?

All I found was:
"JW Player will gradually release v2 capabilities during the second half of 2020 into 2021. During this period, JW Player will maintain full support for both JW Platform Management API v1 and JW Player Platform Management API v2."

Everything is working perfectly for us and we're happy with v1 features so we'd like to avoid upgrading indefinitely if possible.

If v1 will start failing mid-2021 is there a migration guide available?

**Comment by boyntoni** [comment]
Dylan,

Thanks for reaching out, and sorry for the delay in getting back to you.

We have not yet determined an EOL for the V1 Management API, but will continue to support it for the foreseeable future. When we do declare an EOL, we will be sure to provide developers ample time for a full migration. At this point, however, all new functionality will only be available through the V2 APIs.

We are working on a migration plan and will post it to our developer site once its available.
