### ISSUE TITLE
Upload from external URL doesn't work and there's no example or documentation on how to do this.

### ISSUE THREAD

**Issue by ronenmagid** [jwplayer/jwplatform-py#49]
It's critical to be able to upload to JWP via external video URL vs. opening a file stream. JWPPlayer API know how to handle this -- I'm doing the exact same thing from PHP. But I can't find a way to do this from this Python Library.

**Comment by boyntoni** [comment]
HI @ronenmagid,

Sorry for the delay in getting back to you. Below is a code sample showing how to perform an external upload with the new client. We are working on adding more documentation and examples, as well.

```
from jwplatform.client import JWPlatformClient

jw_client = JWPlatformClient("YOUR_V2_API_SECRET")
response = jw_client.Media.create(
    site_id="YOUR_SITE_ID",
    body={
        "upload": {
            "method": "fetch",
            "download_url": "REMOTE_ADDRESS"
        },
        "metadata": {
            "title": "An external upload"
        }
    },
)
print(response.json_body)
```
