### ISSUE TITLE
Auth issues with v2 client

### ISSUE THREAD

**Issue by JacobASeverson** [jwplayer/jwplatform-py#63]
Python version: 3.9.7
Library version: 2.1.3

Using the `JWPlatformClient` produces 401s when trying to list media. Example:

```python
    jwplatform_client = JWPlatformClient(MY_API_SECRET)
    response = jwplatform_client.Media.list(site_id=MY_SITE_ID)
```

Whenever I execute the above code, a request is sent with the following headers:
```
User-Agent: jwplatform_client-python/2.1.3
Authorization: Bearer MY_API_SECRET
Content-Type: application/json
```

and I get a 401 response. I noticed [in the documentation](https://developer.jwplayer.com/jwplayer/reference/get_v2-sites-site-id-media) that `Bearer` is emitted from the `Authorization` header. While debugging, If I remove that part and only send the secret in the `Authorization` header it works as expected.

**Comment by polishmatt** [comment]
The cause of this issue has been resolved.
