### ISSUE TITLE
Make a new gh/pip release

### ISSUE THREAD

**Issue by dylancaponi** [jwplayer/jwplatform-py#66]
There have been several updates and bug fixes [including this one](https://github.com/jwplayer/jwplatform-py/issues/64) that would be nice to have in the official release.

Currently, pip install downloads a version from 2021.

Can someone on the JW team please publish a new release here and on pypi?

Thank you!

**Comment by dylancaponi** [comment]
@polishmatt can you help with this (after the new year 😝 )?

**Comment by polishmatt** [comment]
Hey @dylancaponi the latest release (2.2.2) should have the change you're looking for. It looks like 2.2.1 (with your thumbnail bugfix) wasn't deployed until Oct 17th.
